// ════════════════════════════════════════════════════════════════════════════
// RAMAYANA PS5 — Corpus Importer (Editor-only)
// Reads corpus_data.json (generated by Python pipeline) → Unity ScriptableObjects
// Menu: Tools > Ramayana > Import Corpus
// Reference: civaka-cintamani-ps5/unity/Assets/Scripts/Editor/CorpusImporter.cs
//            (Cīvaka importer is the model)
// ════════════════════════════════════════════════════════════════════════════

#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using Jambudweep.Ramayana.Data;

namespace Jambudweep.Ramayana.Editor
{
    public class CorpusImporter : EditorWindow
    {
        [MenuItem("Tools/Ramayana/Import Corpus", priority = 100)]
        public static void ShowWindow()
        {
            var w = GetWindow<CorpusImporter>("Ramayana Corpus Importer");
            w.minSize = new Vector2(420, 320);
        }

        private string _corpusPath = "Assets/Resources/corpus_data.json";
        private string _outputDir = "Assets/Resources/Generated";

        void OnGUI()
        {
            GUILayout.Label("Ramayana Corpus Importer", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "Reads corpus_data.json (Python output) → creates ActData, CharacterData,\n" +
                "StoryMomentData, and EpisodeData ScriptableObjects.\n\n" +
                "Schema version 1, parity with Cīvaka Cintāmaṇi importer.",
                MessageType.Info);

            EditorGUILayout.Space();
            _corpusPath = EditorGUILayout.TextField("Corpus JSON", _corpusPath);
            _outputDir = EditorGUILayout.TextField("Output Dir", _outputDir);

            EditorGUILayout.Space();
            if (GUILayout.Button("Import Corpus", GUILayout.Height(36)))
            {
                Import();
            }
        }

        private void Import()
        {
            if (!File.Exists(_corpusPath))
            {
                EditorUtility.DisplayDialog("Corpus Importer",
                    $"Corpus file not found:\n{_corpusPath}\n\nRun Tools/corpus_to_unity.py first.", "OK");
                return;
            }

            string json = File.ReadAllText(_corpusPath);
            var corpus = JsonUtility.FromJson<CorpusRoot>(json);
            if (corpus == null)
            {
                EditorUtility.DisplayDialog("Corpus Importer", "Failed to parse corpus JSON.", "OK");
                return;
            }

            Directory.CreateDirectory(_outputDir);

            // Characters
            if (corpus.characters != null)
            {
                foreach (var ch in corpus.characters)
                {
                    var asset = ScriptableObject.CreateInstance<CharacterData>();
                    asset.characterId = ch.characterId;
                    asset.characterName = ch.displayName;
                    asset.tamilName = ch.displayNameTamil;
                    asset.role = ch.role;
                    asset.colorHex = ch.color ?? "#FFFFFF";
                    string assetPath = $"{_outputDir}/Character_{ch.characterId}.asset";
                    AssetDatabase.CreateAsset(asset, assetPath);
                }
            }

            // Acts
            if (corpus.acts != null)
            {
                foreach (var act in corpus.acts)
                {
                    var asset = ScriptableObject.CreateInstance<ActData>();
                    asset.actId = act.actId;
                    asset.actNumber = act.actNumber;
                    asset.title = act.title;
                    asset.location = act.location;
                    asset.scene = ParseScene(act.scene);
                    asset.setup = act.setup;
                    asset.lesson = act.lesson;
                    asset.playerRole = act.playerRole;
                    asset.reward = new ActReward
                    {
                        badge = act.reward?.badge ?? "",
                        lore = act.reward?.lore ?? "",
                        dharma = act.reward?.dharma ?? 0
                    };

                    // Objectives
                    if (act.objectives != null)
                    {
                        asset.objectives = new System.Collections.Generic.List<ObjectiveData>();
                        foreach (var o in act.objectives)
                        {
                            asset.objectives.Add(new ObjectiveData
                            {
                                id = o.id,
                                type = ParseObjectiveType(o.type),
                                title = o.title,
                                marker = o.marker,
                                cue = o.cue,
                                actionLabel = o.actionLabel,
                                completedLine = new ObjectiveCompletedLine
                                {
                                    speaker = o.completedLine?.speaker ?? "",
                                    text = o.completedLine?.text ?? ""
                                },
                                target = o.target,
                                position = new Vec3(o.position?.x ?? 0, o.position?.y ?? 0, o.position?.z ?? 0)
                            });
                        }
                    }

                    // Dialogue
                    if (act.dialogue != null)
                    {
                        asset.dialogue = new System.Collections.Generic.List<DialogueLine>();
                        foreach (var d in act.dialogue)
                        {
                            asset.dialogue.Add(new DialogueLine
                            {
                                speaker = d.speaker,
                                text = d.text,
                                voice = ParseVoice(d.voice)
                            });
                        }
                    }

                    string assetPath = $"{_outputDir}/Act_{act.actNumber}_{act.actId}.asset";
                    AssetDatabase.CreateAsset(asset, assetPath);
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("Corpus Importer",
                $"Imported {corpus.characters?.Length ?? 0} characters, {corpus.acts?.Length ?? 0} acts → {_outputDir}", "OK");
        }

        // ── Parsers (string → enum) ───────────────────────────────────

        private static ObjectiveType ParseObjectiveType(string s)
        {
            switch ((s ?? "").ToLower())
            {
                case "choice": return ObjectiveType.Choice;
                case "talk": return ObjectiveType.Talk;
                case "travel": return ObjectiveType.Travel;
                case "collect": return ObjectiveType.Collect;
                case "use": return ObjectiveType.Use;
                case "witness": return ObjectiveType.Witness;
                case "combat": return ObjectiveType.Combat;
                default: return ObjectiveType.Witness;
            }
        }

        private static RamayanaScene ParseScene(string s)
        {
            switch ((s ?? "").ToLower())
            {
                case "ayodhya": return RamayanaScene.Ayodhya;
                case "panchavati": return RamayanaScene.Panchavati;
                case "kishkindha": return RamayanaScene.Kishkindha;
                case "lanka": return RamayanaScene.Lanka;
                case "setu": return RamayanaScene.Setu;
                case "return": return RamayanaScene.Return;
                case "bala": return RamayanaScene.Bala;
                case "janakpur": return RamayanaScene.Janakpur;
                case "ashram": return RamayanaScene.Ashram;
                case "ocean": return RamayanaScene.Ocean;
                case "ravana-court": return RamayanaScene.RavanaCourt;
                case "earth-return": return RamayanaScene.EarthReturn;
                case "mithila": return RamayanaScene.Mithila;
                case "chitrakuta": return RamayanaScene.Chitrakuta;
                case "nandigram": return RamayanaScene.Nandigram;
                case "sarayu": return RamayanaScene.Sarayu;
                case "lanka-palace": return RamayanaScene.LankaPalace;
                case "lanka-garden": return RamayanaScene.LankaGarden;
                default: return RamayanaScene.Ayodhya;
            }
        }

        private static VoiceRegister ParseVoice(string s)
        {
            switch ((s ?? "").ToLower())
            {
                case "sloka": return VoiceRegister.Sloka;
                case "vaachaka": return VoiceRegister.Vaachaka;
                case "shastriya": return VoiceRegister.Shastriya;
                case "praarthana": return VoiceRegister.Praarthana;
                case "sheershata": return VoiceRegister.Sheershata;
                case "vairagya": return VoiceRegister.Vairagya;
                case "maatru": return VoiceRegister.Maatru;
                case "pratishedha": return VoiceRegister.Pratishedha;
                case "dainya": return VoiceRegister.Dainya;
                case "niti": return VoiceRegister.Niti;
                case "kathaka": return VoiceRegister.Kathaka;
                default: return VoiceRegister.Kathaka;
            }
        }

        // ── JSON deserialization (mirror Python schema) ───────────────

        [System.Serializable]
        private class CorpusRoot
        {
            public string schemaVersion;
            public Character[] characters;
            public Act[] acts;
        }

        [System.Serializable]
        private class Character
        {
            public string characterId;
            public string displayName;
            public string displayNameTamil;
            public string role;
            public string color;
        }

        [System.Serializable]
        private class Act
        {
            public string actId;
            public int actNumber;
            public string title;
            public string location;
            public string scene;
            public string setup;
            public string lesson;
            public string playerRole;
            public Objective[] objectives;
            public Dialogue[] dialogue;
            public Reward reward;
        }

        [System.Serializable]
        private class Objective
        {
            public string id;
            public string type;
            public string title;
            public string marker;
            public string cue;
            public string actionLabel;
            public CompletedLine completedLine;
            public int target;
            public Position position;
        }

        [System.Serializable]
        private class CompletedLine
        {
            public string speaker;
            public string text;
        }

        [System.Serializable]
        private class Position
        {
            public float x, y, z;
        }

        [System.Serializable]
        private class Dialogue
        {
            public string speaker;
            public string text;
            public string voice;
        }

        [System.Serializable]
        private class Reward
        {
            public string badge;
            public string lore;
            public int dharma;
        }
    }
}
#endif
